services:
  analysis:
    image: ${IMAGE_NAME}
    build:
      context: .
      args:
        GIT_BRANCH_NAME: ${GIT_BRANCH_NAME}
        APP_DIR_NAME: ${APP_DIR_NAME}      
        GITHUB_URI: ${GITHUB_URI}      
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
      - 8000:8000
    depends_on:
      - mongodb
    command:
      - "jupyter"
      - "lab"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--allow-root"
      - "--NotebookApp.token=''"
      - "--NotebookApp.notebook_dir='/app'"      
  mongodb:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
